# SPDX-FileCopyrightText: 2019 Saalim Quadri <danascape@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later

version = 1
SPDX-PackageName = "sworkflow"
SPDX-PackageSupplier = "Saalim Quadri"
SPDX-PackageDownloadLocation = "https://github.com/sworkflow-project/sworkflow"

[[annotations]]
path = [".github/workflows/**", ".gitignore", "configs/**", "**/files", "**/*.md", "debian/**", "man/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 Saalim Quadri <danascape@gmail.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["utils/mkdtboimg.py"]
precedence = "override"
SPDX-FileCopyrightText = "2017, The Android Open Source Project"
SPDX-License-Identifier = "Apache-2.0"
