name: ShellCheck scripts
on:
  [push, pull_request]

jobs:
  shellCheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Run shellcheck.
      run: while read -r script; do shellcheck --exclude=SC1090,SC1091 $script; done < tests/files
